name: gh_pages_update

on:
  push:
    branches:
      - french-released

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish-book:
    name: Publish book on Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update rustup
        run: rustup self update

      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain install 1.90 -c rust-docs
          rustup default 1.90

      - name: Install mdbook
        run: |
          mkdir bin
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.52/mdbook-v0.4.52-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
          echo "$(pwd)/bin" >> ${GITHUB_PATH}

      - name: Report versions
        run: |
          rustup --version
          rustc -Vv
          mdbook --version

      - name: Run build
        run: mdbook build FRENCH

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'FRENCH/book'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
